---
version: "2.1"
services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile-code-server
    container_name: commune
    shm_size: '1gb' # for the shared memory size
    volumes:
      - ~/.commune:/config/.commune
      - ~/.commune:/root/.commune
      - ./:/workspace
      #- /var/run/docker.sock:/var/run/docker.sock #Nuclear option
    ports:
      - 10000:8443
    restart: unless-stopped